
api_version = "unstable"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "dropdeck-preorder-purchase-option"
type = "ui_extension"
url = "/create-preorder"

# Both targets need to be specified for the extensions to work
[[extensions.targeting]]
module = "./src/product-extension.tsx"
target = "admin.product-purchase-option.action.render"

[[extensions.targeting]]
module = "./src/product-variant-extension.tsx"
target = "admin.product-variant-purchase-option.action.render"

# Valid extension targets:

# Product index and detail pages
# - admin.product-purchase-option.action.render

# Product variant detail pages
# - admin.product-variant-purchase-option.action.render
