# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e42a64a0fc2480cc7eec789e0caed811"
name = "Dropdeck (Development)"
handle = "dropdeck-development"
application_url = "https://ccd-yarn-retrieval-caught.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/order-create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/order-updated"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_own_subscription_contracts,read_products,read_purchase_options,write_app_proxy,write_orders,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://ccd-yarn-retrieval-caught.trycloudflare.com/auth/callback",
  "https://ccd-yarn-retrieval-caught.trycloudflare.com/auth/shopify/callback",
  "https://ccd-yarn-retrieval-caught.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://ccd-yarn-retrieval-caught.trycloudflare.com/app/api-proxy"
subpath = "px"
prefix = "apps"

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
