# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7335e14a94732885ca09f94e73497e98"
name = "Dropdeck"
handle = "dropdeck"
application_url = "https://affordable-you-beijing-programme.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://affordable-you-beijing-programme.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://affordable-you-beijing-programme.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://affordable-you-beijing-programme.trycloudflare.com/webhooks/order-create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "https://affordable-you-beijing-programme.trycloudflare.com/webhooks/order-updated"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_own_subscription_contracts,read_products,read_purchase_options,write_app_proxy,write_own_subscription_contracts,write_products,write_purchase_options,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://affordable-you-beijing-programme.trycloudflare.com/auth/callback",
  "https://affordable-you-beijing-programme.trycloudflare.com/auth/shopify/callback",
  "https://affordable-you-beijing-programme.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://affordable-you-beijing-programme.trycloudflare.com/app/api-proxy"
subpath = "px"
prefix = "apps"

[pos]
embedded = false
