# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7335e14a94732885ca09f94e73497e98"
name = "Dropdeck"
handle = "dropdeck"
application_url = "https://actively-workshop-animal-kings.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, write_metaobjects, read_metaobjects, read_metaobject_definitions, write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://actively-workshop-animal-kings.trycloudflare.com/auth/callback",
  "https://actively-workshop-animal-kings.trycloudflare.com/auth/shopify/callback",
  "https://actively-workshop-animal-kings.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
